name: CI

on:
  push: ~
  pull_request: ~
  schedule:
    - cron: '0 12 * * *'

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ['12.17', 16.x]
        os: ['ubuntu-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
